global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "backend:8000"

  - job_name: "prometheus"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "node-exporter"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "node-exporter:9100"

  - job_name: "grafana"
    scrape_interval: 5s
    metrics_path: "/grafana/metrics"
    static_configs:
      - targets:
          - "grafana:3000"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alert.rules.yml"
